### ISSUE TITLE
Trouble building project with Node 16.x

### ISSUE THREAD

**Issue by MalikKillian** [budgetzero/budgetzero#99]
I've tried two different ways to build this project using 16.x (local installation and Docker image). Each one has a different error and I don't think the errors are very clear. If nobody else is having trouble with 16.x I'll post my output. Otherwise it might be a good idea to limit the recommended engine to 12 or 14.

You can do it with a few changes like this: https://stackoverflow.com/a/29349773/1255267

**Comment by MalikKillian** [comment]
I didn't have issues building with Node 12 and 14 btw.

**Comment by tedtms** [comment]
What error(s) are you getting? I'm having trouble building too, but the error I'm getting is deasync related.

**Comment by atomdmac** [comment]
I've been having a heck of a time getting this to build on `12.x` or `17.x`.

On `17.x` I run `npm i` to install (which works well aside from the dep package security warnings).  Then when I run `npm run serve` or `npm run build` I get:

```
/home/atom/Code/budgetzero/node_modules/electron/index.js:17
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
```

This appears to be because `electron` doesn't generate a `path.txt` file in `/node_modules/electron` so the module can't find the binary.  If I create one manually and point it to `./node_modules/.bin/electron`, re-running either of the above command yields:

```
> budgetzero@0.1.21 serve
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/3 modules 1 active ...e/atom/Code/budgetzero/src/main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/atom/Code/budgetzero/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/atom/Code/budgetzero/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/atom/Code/budgetzero/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/atom/Code/budgetzero/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/atom/Code/budgetzero/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/atom/Code/budgetzero/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/atom/Code/budgetzero/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
10% building 2/5 modules 3 active ..._modules/webpack/hot/dev-server.jsnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/atom/Code/budgetzero/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/atom/Code/budgetzero/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/atom/Code/budgetzero/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/atom/Code/budgetzero/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/atom/Code/budgetzero/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/atom/Code/budgetzero/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/atom/Code/budgetzero/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/atom/Code/budgetzero/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/atom/Code/budgetzero/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
``

**Comment by stefanjf** [comment]
I have it working on various environments (windows WSL, ubuntu, github codespaces, etc) using node 12.x, 14.x, and 16.x. Have not tested 17.x. 

I wonder if some OS's are causing some issues with certain packages during install. 

Electron is only needed for the desktop apps, not for the web versions, so we could always create a branch stripping those dependencies if it's troublesome.

**Comment by atomdmac** [comment]
@stefanjf I'm ambivalent to the presence of Electron myself but if stripping that stuff out would help alleviate the pain points around the built, I would personally find that to be really useful.  I'd like to play around with the code and possibly contribute if the opportunity arises but currently, I can't get it to build.

**Comment by atomdmac** [comment]
Just wanted to report that I was able to build successfully on MacOS using Node `14.15.0`.

The system I was having trouble with yesterday was a Linux (PopOS) installation so the OS may have something to do with it.  I'll give Node 14.x a try on that system later this week and see if I can get it to work.

**Comment by rafiazman** [comment]
I was able to build on macOS with Node `16.14.1`. It would probably be best to add a `.nvmrc` file to fix the Node version used for development.

https://github.com/nvm-sh/nvm#nvmrc

**Comment by MalikKillian** [comment]
Haven't looked at this issue in a while but I was just able to build and run the latest codebase using Node `v16.15.1`. This is running the web version btw, not Electron (which I personally don't plan to use).

I'm fine with closing this.
